ARG NODE_VERSION

FROM golang:1.21-alpine as builder
RUN apk add --no-cache git
WORKDIR /root/
RUN go install github.com/google/pprof@latest

FROM node:${NODE_VERSION}-alpine

ARG ADDITIONAL_PACKAGES
# Force ipv4 results first b/275122541
ENV NODE_OPTIONS="--dns-result-order=ipv4first"

RUN apk add --no-cache bash $ADDITIONAL_PACKAGES
WORKDIR /root/
COPY --from=builder /go/bin/pprof /bin
RUN chmod a+x /bin/pprof
