FROM golang:1.12-alpine as builder
RUN apk update && apk upgrade && apk add --no-cache git
WORKDIR /root/
RUN go get github.com/google/pprof


FROM node:8-alpine

ARG BUILD_BINARIES

RUN apk update && apk upgrade && apk add --no-cache bash
RUN if [ "$BUILD_BINARIES" = "true" ] ; then apk add --no-cache python g++ make ; fi
WORKDIR /root/
COPY --from=0 /go/bin/pprof /bin
RUN chmod a+x /bin/pprof
