FROM golang:1.16-alpine as builder
RUN apk add --no-cache git
WORKDIR /root/
RUN go get github.com/google/pprof


FROM node:15-alpine

ARG ADDITIONAL_PACKAGES

RUN apk add --no-cache bash $ADDITIONAL_PACKAGES
WORKDIR /root/
COPY --from=builder /go/bin/pprof /bin
RUN chmod a+x /bin/pprof
