name: Release

on:
  push:
    branches:
      - main
      - v[0-9]+.x

jobs:
  build:
    uses: Datadog/action-prebuildify/.github/workflows/build.yml@main
    with:
      target-name: 'dd_pprof' # target name in binding.gyp
      package-manager: 'npm' # npm or yarn
      cache: true # enable caching of dependencies based on lockfile
      min-node-version: 18
      skip: 'linux-arm,linux-ia32' # skip building for these platforms
      node-gyp-build-major: 4

  publish_release:
    needs: build
    runs-on: ubuntu-latest
    # release.yml also runs on main for dev publishes, so keep release publishes on version branches only.
    if: startsWith(github.ref, 'refs/heads/v')
    environment: npm
    permissions:
      id-token: write # Required for OIDC
      contents: write
    steps:
      - uses: DataDog/dd-octo-sts-action@acaa02eee7e3bb0839e4272dacb37b8f3b58ba80 # v1.0.3
        id: octo-sts
        with:
          scope: DataDog/pprof-nodejs
          policy: self.github.release.push-tags
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/download-artifact@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm publish
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "json=$content" >> $GITHUB_OUTPUT
      - run: |
          git tag v${{ fromJson(steps.pkg.outputs.json).version }}
          git push https://x-access-token:${{ steps.octo-sts.outputs.token }}@github.com/${{ github.repository }}.git v${{ fromJson(steps.pkg.outputs.json).version }}

  publish_dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: npm
    permissions:
      id-token: write # Required for OIDC
      contents: read
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/download-artifact@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - id: pkg
        run: |
          content=`cat ./package.json | tr '\n' ' '`
          echo "json=$content" >> $GITHUB_OUTPUT
      - run: npm version --no-git-tag-version ${{ fromJson(steps.pkg.outputs.json).version }}-$(git rev-parse --short HEAD)+${{ github.run_id }}.${{ github.run_attempt }}
      - run: npm publish --tag dev
